fix: Improve nc_link_app checkout
Signed-off-by: Louis Chemineau <louis@chmn.me>

diff --git a/nc_link_app b/nc_link_app
--- a/nc_link_app
+++ b/nc_link_app
@@ -54,8 +54,14 @@ fi
 
 if [ ! -d "$workspace/instances/$instance/apps-extra/$app" ]
 then
-	git -C "$workspace/apps/$app" worktree add --force "$workspace/instances/$instance/apps-extra/$app" "$instance"
+	git -C "$workspace/apps/$app" worktree add --quiet --force "$workspace/instances/$instance/apps-extra/$app" "$instance" ||
+	git -C "$workspace/apps/$app" worktree add --quiet --force "$workspace/instances/$instance/apps-extra/$app" "main" ||
+	git -C "$workspace/apps/$app" worktree add --quiet --force "$workspace/instances/$instance/apps-extra/$app" "master"
 fi
+
+git -C "$workspace/instances/$instance/apps-extra/$app" fetch --force --tags --prune --prune-tags --recurse-submodules --quiet || echo "Failed to fetch $app"
+git -C "$workspace/instances/$instance/apps-extra/$app" pull --quiet || echo "Failed to pull $app"
+composer --quiet --working-dir "$workspace/instances/$instance/apps-extra/$app" install
 
 cd "$workspace/instances/$instance"
 php ./occ app:enable "$app"
